### ISSUE TITLE
Angry Face class perk correction

### ISSUE THREAD

**Issue by SoccerCore11** [jason-whitted/gloomy#46] opened 2018-05-08 20:57 UTC
The second perk should be +1, not +2
https://i.imgur.com/iagXLfy.jpg

**Comment by jason-whitted** [comment] 2018-05-11 01:02
This has been fixed in 0.1.18.

NOTE: It was using the wrong Perk ID, which means if you purchased one of these perks it will no longer show up and you will **not** get credit for an additional perk.  You will need to find where you purchased the invalid perk in your campaign History and `Delete` the history item to be able to purchase the new perk ID.

**Closed by jason-whitted** 2018-05-11 01:02 UTC
Labels: bug, resolved

**Comment by SoccerCore11** [comment] 2018-05-11 12:00
Thanks. I don't think those perks were as selected, but I could no longer access this character after the most recent update, it kept giving me the 'magic button'. I tried deleting all of that classes perks from the history, and that didn't work either. Then I tried deleting the character from the history, and now my entire party won't load. Help! How do I get back into my campaign/party? I'm stuck in a magic button loop. Is there any way I can rebuild?

**Comment by jason-whitted** [comment] 2018-05-11 12:29
I’ll need your campaign ID. Then I can look at it directly and figure out what the problem is. Sorry for the headache, but I will get you squared away.

**Comment by SoccerCore11** [comment] 2018-05-11 23:57
cf97b21b6bdfe90035c740a1bf3b2c83
Thanks!

**Comment by jason-whitted** [comment] 2018-05-12 08:42
@SoccerCore11, When you deleted the character, it broke the relationship with everything that was pointing to it.  You'll need to manually update the campaign in order to delete these rogue deletions.  I'll walk you through the process.

1. Navigate to [https://gist.github.com](https://gist.github.com)
1. Click on the `ABOUT.md` for the campaign you need to edit.  In your case it is 'The First Campaign'
1. Click `Edit`
1. In the `gloomy.campaign.js` file scroll to the very bottom
1. You need to delete the `DeleteAction` entries at the end.  I see 11 of them (lines 191-201).  Delete those lines entirely.

:star: **IMPORTANT!**  :star: The last two characters of the file should be `]}`
If the last character of your file is a comma, replace the `,` with `]}`

# Example:
## Before deletions
```js
{"history":[
  {"action":"PlayerCreate","payload":{"name":"Phrozen"},"dt":"2018-04-21T19:25:57Z","id":2564335,"by":"SoccerCore11"},
  ...
  {"action":"CharacterBuyItem","payload":{"character":2582089,"item":13},"dt":"2018-05-09T01:12:53Z","id":2583265,"by":"SoccerCore11"},
  {"action":"DeleteAction","payload":{"id":2583265},"dt":"2018-05-09T01:14:56Z","id":2583267,"by":"SoccerCore11"},
  {"action":"DeleteAction","payload":{"id":2583264},"dt":"2018-05-11T11:49:38Z","id":2586010,"by":"SoccerCore11"},
  {"action":"DeleteAction","payload":{"id":2583239},"dt":"2018-05-11T11:49:45Z","id":2586011,"by":"SoccerCore11"},
  {"action":"DeleteAction","payload":{"id":2583237},"dt":"2018-05-11T11:49:51Z","id":2586012,"by":"SoccerCore11"},
  {"action":"DeleteAction","payload":{"id":2583232},"dt":"2018-05-11T11:50:00Z","id":2586013,"by":"SoccerCore11"},
  {"action":"DeleteAction","payload":{"id":2582099},"dt":"2018-05-11T11:50:20Z","id":2586014,"by":"SoccerCore11"},
  {"action":"DeleteAction","payload":{"id":2582098},"dt":"2018-05-11T11:50:29Z","id":2586015,"by":"SoccerCore11"},
  {"action":"DeleteAction","payload":{"id":2582092},"dt":"2018-05-11T11:50:36Z","id":2586016,"by":"SoccerCore11"},
  {"action":"DeleteAction","payload":{"id":2582091},"dt":"2018-05-11T11:50:45Z","id":2586017,"by":"SoccerCore11"},
  {"action":"DeleteAction","payload":{"id":2582090},"dt":"2018-05-11T11:50:54Z","id":2586018,"by":"SoccerCore11"},
  {"action":"DeleteAction","payload":{"id":2582089},"dt":"2018-05-11T11:52:01Z","id":2586019,"by":"SoccerCore11"}]}
```

## After deletions
```js
{"history":[
  {"action":"PlayerCreate","payload":{"name":"Phrozen"},"dt":"2018-04-21T19:25:57Z","id":2564335,"by":"SoccerCore11"},
  ...
  {"action":"CharacterBuyItem","payload":{"character":2582089,"item":13},"dt":"2018-05-09T01:12:53Z","id":2583265,"by":"SoccerCore11"}]}
```

Once complete you can just click `Update secret gist` and when you refresh the campaign in Gloomy it should load properly.   If you run into any problems, let me know.

**Comment by SoccerCore11** [comment] 2018-05-12 16:59
Thanks so much for the detailed instructions, I'm back up and running!
